import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";

import RootProvider from '../providers';

import { authOptions } from "../lib/authOptions";

import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function  RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
          <RootProvider session={session}>
              {children}
          </RootProvider>
        </body>
    </html>
  );
}
